# Site settings
title:          Khanh Nguyen Van
description:    "Phàm nhân tu tiên tới bất diệt truyền thuyết"
url:            "https://khanhnv2901.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Khanh Nguyen Van
  url:          https://khanhnv2901.github.io
  email:        khanhnv2901@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]




kramdown:
  parse_block_html: true
  
comments:
	provider : "facebook"
	facebook:
		appid : 305066621194941
		num_posts : # 5 (default)
		colorscheme : # "light" (default), "dark"

comments: true
