# Site settings
title:          Khanh Nguyen Van
description:    "Phàm nhân tu tiên tới bất diệt truyền thuyết"
url:            "https://khanhnv2901.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Khanh Nguyen Van
  url:          https://khanhnv2901.github.io
  email:        khanhnv2901@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]


comments: true

kramdown:
  parse_block_html: true

  toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
    
defaults:
  - scope:
      path: ""
    values:
      toc: true